services:
  backend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: npx ts-node /app/src/index.ts
    volumes:
      - .:/app
    tty: true
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432